[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'disorder-kit'
version = '0.1.0'
dependencies = [
    'requests',
    'biopython',
    'aiupred @ git+https://github.com/doszilab/AIUPred.git',
    'typer',
    'pandas',
    'numpy',
    'plotly'
]

[tool.setuptools]
package-dir = {'' = 'src'}

[tool.setuptools.packages.find]
where = ['src']

[project.scripts]
disorder-compare = "disorder_kit.disorder_compare.cli:app"